# Generated by Django 4.2 on 2023-04-25 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_rename_prettynum_phonenumbers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="creat_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 4, 25, 21, 30, 59, 124460),
                null=True,
                verbose_name="入职时间",
            ),
        ),
    ]
