# Generated by Django 4.2 on 2023-05-03 13:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_task_alter_userinfo_creat_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.myadmin",
                verbose_name="负责人",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="creat_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 5, 3, 21, 3, 5, 915440),
                null=True,
                verbose_name="入职时间",
            ),
        ),
    ]
