# Generated by Django 4.2 on 2023-05-03 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_alter_userinfo_creat_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="creat_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 5, 3, 21, 18, 23, 345789),
                null=True,
                verbose_name="入职时间",
            ),
        ),
    ]
