# Generated by Django 4.2 on 2023-05-06 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_alter_userinfo_creat_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="creat_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 5, 6, 20, 59, 57, 601976),
                null=True,
                verbose_name="入职时间",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "oid",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="订单号",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="价格",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "待支付"), (2, "支付中"), (3, "已支付")],
                        null=True,
                        verbose_name="状态",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.myadmin",
                        verbose_name="管理员",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.userinfo",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
